engines:
  duplication:
    enabled: false
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/Superglobals:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: true
      Design/WeightedMethodCount:
        enabled: true
      CleanCode/StaticAccess:
        enabled: false
      Design/TooManyPublicMethods:
        enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- "/tests"
- "/Documentation"
exclude_patterns:
- "**Interface.php"