engines:
  duplication:
    enabled: false
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/BooleanArgumentFlag:
        enabled: true
      Design/WeightedMethodCount:
        enabled: true
      CleanCode/StaticAccess:
        enabled: true
      Design/TooManyPublicMethods:
        enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.php"
exclude_paths:
- "/tests"
- "/Documentation"
