language: php
php:
  - '7.0'
  - '5.6'
  - '5.5'
  - '5.4'
  - hhvm

before_script:
    - composer self-update
    - composer install
    
script:
    - mkdir -p build/logs 
    - phpunit --coverage-clover build/logs/clover.xml
    - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then vendor/bin/phpcs ; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then vendor/bin/test-reporter ; fi