language: php
sudo: required
php:
  - '7.1'
  - '7.0'

env:
  global:
    - MYSQL_CONN="host=localhost;dbname=travis_ci_test;user=root;password="
    - PG_CONN="host=localhost;port=5432;dbname=travis_ci_test;user=postgres;password="

addons:
   - postgresql: "9.5"
   - mariadb: '10.0'

before_script:
    - mysql -e 'CREATE DATABASE travis_ci_test;'
    - psql -c 'create database travis_ci_test;' -U postgres
    - if [[ "$TRAVIS_OS_NAME" == 'linux' ]] ; then sudo apt-get install rsync ; fi
    - touch travis.php.ini
    - sudo chmod 0777 travis.php.ini
    - pecl config-set php_ini travis.php.ini
    - pear config-set php_ini travis.php.ini
    - phpenv config-add travis.php.ini
 #   - composer self-update
    - composer install
 #   - sleep 15
 #   - mongo localhost:27017/gishiki ./tests/SetupTestingMongo.js

script:
    - mkdir build && mkdir build/logs
    - composer test
    
after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then php vendor/bin/codacycoverage clover build/logs/clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then ./vendor/bin/test-reporter ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer remove symfony/yaml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer remove zendframework/zend-diactoros ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer remove codacy/coverage --dev ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer remove codeclimate/php-test-reporter --dev  ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer remove squizlabs/php_codesniffer --dev ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer remove phpunit/phpunit --dev ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then rm -rf ./vendor/ composer.lock ;fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer require roave/better-reflection dev-master#a402048 --dev ;fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer require apigen/apigen 5.0.0-RC5 --dev ;fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then vendor/bin/apigen generate src --destination Documentation/docs/API ;fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py && sudo pip install mkdocs ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then cd Documentation && mkdocs build && cd ../ ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then cd Documentation && git clone -b gh-pages $GIT_REMOTE ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then rsync -avh --progress ./site/ ./Gishiki ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then git config --global user.email "benato.denis96@gmail.com" && git config --global user.name "Denis Benato" && git config --global push.default matching  ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then cd Gishiki &&  git add * && git commit -m "deploy doc from commit $TRAVIS_BRANCH ( $TRAVIS_COMMIT ) " && git push ; fi
