site_name: Gishiki

pages:
- Home: index.md
- Installation: installation.md
- API: apidoc.md
- Usage:
    - Router: usage/routing.md
    - Logger: usage/logging.md

- About:
    - License: license.md

theme: readthedocs
